---
name: Zuri
description: Zuri is an anticheat made to protect the server from any may unfair advantages from the players.
authors: [ReinfyTeam, xqwtxon, xwertxy, UnknownNull]
version: 1.1.2
website: "https://github.com/ReinfyTeam/Zuri/"
main: ReinfyTeam\Zuri\APIProvider
api: 5.0.0
permissions:
     zuri.command:
          default: op
          description: Zuri command.
...
