---
name: Zuri 
description: A powerful anticheat made to destroy hackers from your server for PocketMine-MP.
authors: [ReinfyTeam, xqwtxon, xwertxy, UnknownNull]
version: 1.2.1 
website: "https://github.com/ReinfyTeam/Zuri/"
src-namespace-prefix: ReinfyTeam\Zuri
main: ReinfyTeam\Zuri\ZuriAC
api: 5.0.0
permissions:
     zuri.command:
          default: op
          description: Zuri command.
...
