---
name: Zuri
description: A powerful anticheat made to destroy hackers from your server for PocketMine-MP.
authors: [ReinfyTeam, xqwtxon, xwertxy, UnknownNull]
version: 1.3.5-BETA
website: "https://github.com/ReinfyTeam/Zuri/"
src-namespace-prefix: ReinfyTeam\Zuri
main: ReinfyTeam\Zuri\ZuriAC
depends: [vosaka, vosaka-come-to-pmmp]
api: 5.0.0
permissions:
     zuri.command:
          default: op
          description: Zuri main command.
...
