# Zuri Anticheat v2.0.0
# Copyright (c) 2024-2026 ReinfyTeam

zuri:
  config-version: 2.0.0
  # Asynchronous processing settings
  # Adjust these values based on your server's performance and workload.
  async:
    # The number of checks to process in each batch. Higher values may improve performance but can increase latency.
    batch_size: 128
    # The maximum number of worker threads to use for asynchronous processing. More workers can handle more batches simultaneously but may consume more resources.
    max_worker: 4