name: Build Phar with Virions

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup PHP for PocketMine-MP
        uses: pmmp/setup-php-action@3.2.0
        with:
          php-version: 8.4
          pm-version-major: 5

      - name: Build plugin phar
        run: php -d phar.readonly=0 tools/build.php

      - name: Upload build artifact
        uses: actions/upload-artifact@v7
        with:
          name: zuri-phar
          path: build/*.phar
          if-no-files-found: error
