name: Build phar package.
run-name: Build phar package with pharynx
on: [push]
jobs:
  build-phar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository.
        uses: actions/checkout@v4
      - name: Download php-binaries.
        run: "curl -sL https://github.com/pmmp/PHP-Binaries/releases/download/pm5-php-8.4-latest/PHP-8.4-Linux-x86_64-PM5.tar.gz -o php.tar.gz"
      - name: Extract php-binaries.
        run: "tar -xvzf php.tar.gz"
      - name: chmod the php-binaries.
        run: "chmod +x ./bin/php7/bin/php"
      - name: Fix opcache.so
        run: |
          EXTENSION_DIR=$(find "$(pwd)/bin" -name "*debug-zts*")
          grep -q '^extension_dir' bin/php7/bin/php.ini && sed -i'bak' "s{^extension_dir=.*{extension_dir=\"$EXTENSION_DIR\"{" bin/php7/bin/php.ini || echo "extension_dir=\"$EXTENSION_DIR\"" >> bin/php7/bin/php.ini
      - name: Install php-cs-fixer.
        run: "curl -sL https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/releases/latest/download/php-cs-fixer.phar -o php-cs-fixer.phar"
      - name: Run php-cs-fixer.
        run: "./bin/php7/bin/php php-cs-fixer.phar fix src"
      - name: Install composer.phar
        run: "curl -sL https://getcomposer.org/download/latest-stable/composer.phar -o composer.phar"
      - name: Install dependencies.
        run: "./bin/php7/bin/php -dphar.readonly=0 composer.phar install --no-dev --no-interaction"
      - name: Build the Zuri.phar using pharynx
        run: "./bin/php7/bin/php -dphar.readonly=0 composer.phar run-script --no-dev build"
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: Zuri Build Phar
          path: Zuri.phar
      - name: Upload build information artifact.
        uses: actions/upload-artifact@v4
        with:
          name: Build information
          path: build_info.json
      - name: Codespace Cleanup
        run: "rm -rf *"

  build-poggit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository.
        uses: actions/checkout@v4
      - name: Download php-binaries.
        run: "curl -sL https://github.com/pmmp/PHP-Binaries/releases/download/pm5-php-8.4-latest/PHP-8.4-Linux-x86_64-PM5.tar.gz -o php.tar.gz"
      - name: Extract php-binaries.
        run: "tar -xvzf php.tar.gz"
      - name: chmod the php-binaries.
        run: "chmod +x ./bin/php7/bin/php"
      - name: Fix opcache.so
        run: |
          EXTENSION_DIR=$(find "$(pwd)/bin" -name "*debug-zts*")
          grep -q '^extension_dir' bin/php7/bin/php.ini && sed -i'bak' "s{^extension_dir=.*{extension_dir=\"$EXTENSION_DIR\"{" bin/php7/bin/php.ini || echo "extension_dir=\"$EXTENSION_DIR\"" >> bin/php7/bin/php.ini
      - name: Install php-cs-fixer.
        run: "curl -sL https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/releases/latest/download/php-cs-fixer.phar -o php-cs-fixer.phar"
      - name: Run php-cs-fixer.
        run: "./bin/php7/bin/php php-cs-fixer.phar fix src"
      - name: Install composer.phar
        run: "curl -sL https://getcomposer.org/download/latest-stable/composer.phar -o composer.phar"
      - name: Install dependencies.
        run: "./bin/php7/bin/php -dphar.readonly=0 composer.phar install --no-dev --no-interaction"
      - name: Build with pharynx
        run: "./bin/php7/bin/php -dphar.readonly=0 composer.phar run-script --no-dev build-source"
      - name: Move .poggit.yml to output folder.
        run: "mv .poggit.yml ./output/"
      - name: Push build from other branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build
          FOLDER: ./output/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Zuri Poggit Build: ({sha}) {msg}"
      - name: Codespace Cleanup
        run: "rm -rf *"
