name: PHP-CS-FIXER Analyze Code Style

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup PHP for PocketMine-MP
        uses: pmmp/setup-php-action@3.2.0
        with:
          php-version: 8.2
          pm-version-major: 5

      - name: Install composer dependencies
        run: composer install --prefer-dist

      - name: Run PHP-CS-FIXER
        run: composer run-script format:check