name: Analyze PHP code with PHPStan

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  phpstan:
    name: Run PHPStan at maximum level
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Set up PHP for PocketMine-MP
        uses: pmmp/setup-php-action@3c38c259834f945351a662392836d90eb08abff0
        with:
          php-version: 8.2
          pm-version-major: 5

      - name: Install Composer dependencies
        run: composer install --prefer-dist

      - name: Run PHPStan at maximum level
        run: composer run-script analyze
